apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "product-service.fullname" . }}-config
  labels:
    {{- include "product-service.labels" . | nindent 4 }}
data:
  SPRING_DATA_MONGODB_URI: {{ .Values.env.mongodbUri | quote }}
  LOKI_URL: {{ .Values.env.lokiUrl | quote }}
  MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: {{ .Values.env.tempoUrl | quote }}
  JAVA_TOOL_OPTIONS: "-Xms128m -Xmx256m -XX:MaxMetaspaceSize=128m"
