apiVersion: v1
kind: Secret
metadata:
  name: {{ include "notification-service.fullname" . }}-mail-secret
  labels:
    {{- include "notification-service.labels" . | nindent 4 }}
type: Opaque
data:
  SPRING_MAIL_USERNAME: {{ .Values.mail.username | b64enc | quote }}
  SPRING_MAIL_PASSWORD: {{ .Values.mail.password | b64enc | quote }}
