apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "api-gateway.fullname" . }}-config
  labels:
    {{- include "api-gateway.labels" . | nindent 4 }}
data:
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER-URI: {{ .Values.env.keycloakIssuerUri | quote }}
  LOKI_URL: {{ .Values.env.lokiUrl | quote }}
  MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: {{ .Values.env.tempoUrl | quote }}
  PRODUCT_SERVICE_URL: {{ .Values.env.productServiceUrl | quote }}
  ORDER_SERVICE_URL: {{ .Values.env.orderServiceUrl | quote }}
  INVENTORY_SERVICE_URL: {{ .Values.env.inventoryServiceUrl | quote }}
  JAVA_TOOL_OPTIONS: "-Xms128m -Xmx256m -XX:MaxMetaspaceSize=128m"
