apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "inventory-service.fullname" . }}-config
  labels:
    {{- include "inventory-service.labels" . | nindent 4 }}
data:
  SPRING_DATASOURCE_URL: {{ .Values.env.datasourceUrl | quote }}
  SPRING_DATASOURCE_USERNAME: {{ .Values.env.datasourceUsername | quote }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.env.datasourcePassword | quote }}
  LOKI_URL: {{ .Values.env.lokiUrl | quote }}
  MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: {{ .Values.env.tempoUrl | quote }}
  JAVA_TOOL_OPTIONS: "-Xms128m -Xmx256m -XX:MaxMetaspaceSize=128m"
